### ISSUE TITLE
Pre-commit githooks

### ISSUE THREAD

**Issue by cobasajaxinpho** [coverlet-coverage/coverlet#1412]
Hi i was trying to setup a coverage checker whereby if fall under 80 %, they won't able to commit it.

somehow result specified is under 80% but still consider success.
Need some suggestion is it a correct way to do that?

dotnet version: 7.0.100
OS: Mac OS ventura m1 Chip

code specified in pre-commit:

dotnet test /p:CollectCoverage=true /p:Threshold=80 /p:ThresholdType=line
rc=$?
if [[ $rc != 0 ]]; then
  # A non-zero return code means an error occurred, so tell the user and exit
  echo "${RED}Unit tests failed, please fix and push again${NC}"
  echo ""
  exit $rc
fi

Result:

+-----------------+-------+--------+--------+
| Module          | Line  | Branch | Method |
+-----------------+-------+--------+--------+
| WebApplication2 | 15.9% | 16.66% | 20%    |
+-----------------+-------+--------+--------+

+---------+-------+--------+--------+
|         | Line  | Branch | Method |
+---------+-------+--------+--------+
| Total   | 15.9% | 16.66% | 20%    |
+---------+-------+--------+--------+
| Average | 15.9% | 16.66% | 20%    |
+---------+-------+--------+--------+

Successfully commited.

**Comment by daveMueller** [comment]
At first sight it seems correct what you are doing. Could you provide a small repro for that?

**Comment by cobasajaxinpho** [comment]
> At first sight it seems correct what you are doing. Could you provide a small repro for that?

Hi Dave.


https://github.com/cobasajaxinpho/Testor

Can try link above for your reference.

**Comment by daveMueller** [comment]
Thanks @cobasajaxinpho 🙏

**Comment by daveMueller** [comment]
OK I continued investigating this a bit today. It seems like for the `msbuild` driver the parameters aren't passed to the `CoverageResultTask` anymore if there is a .NET 7 SDK installed. This is a known issue here [https://github.com/coverlet-coverage/coverlet/issues/1391](https://github.com/coverlet-coverage/coverlet/issues/1391). Thus the `Threshold` currently is always 0. 

In the link are also some workarounds if you need to use `msbuild` driver. As alternative you could also use the global tool where the `Threshold` feature is also working.

![grafik](https://user-images.githubusercontent.com/19378678/205404727-cb95657f-f7b1-4b9f-a77b-a881780d0ccc.png)

**Comment by cobasajaxinpho** [comment]
Hi Dave,

Thanks for the response, you mean we need to install the coverlet console global version is it?

**Comment by daveMueller** [comment]
Hi the issue was fixed by the microsoft guys with sdk 7.0.101 that was released last week microsoft/vstest#4014. I just checked it with your repro and it works fine. Please give it a try again.

**Comment by cobasajaxinpho** [comment]
just tried on mac still having the same issue. haha.. you are using mac or windows ?

**Comment by daveMueller** [comment]
I tried it on windows and linux. Are you sure sdk 7.0.101 is installed? Unfortunately I don't have a Mac and can't test it there.

Windows:
![grafik](https://user-images.githubusercontent.com/19378678/209239070-0542aeb0-78c8-45cf-8a02-8734023c7e12.png)

Linux (basic docker image [mcr.microsoft.com/dotnet/sdk:7.0]):
![grafik](https://user-images.githubusercontent.com/19378678/209239197-09391ab4-165f-4b12-bde5-d78f1527ee57.png)

**Comment by daveMueller** [comment]
@cobasajaxinpho Are you still facing this issue even though the sdk is now on 7.0.202?

**Comment by Bertk** [comment]
Please verify whether the problem still exists using the latest [coverlet 6.0.2 release](https://www.nuget.org/packages?q=coverlet).
